[[headers]]
  for = "/*"
  [headers.values]
    content-security-policy = "base-uri 'self'; child-src 'self'; connect-src 'self' https://localhost:8000 wss://localhost:8000 https://resen-reactjs-api.onrender.com wss://resen-reactjs-api.onrender.com https://www.google-analytics.com; default-src 'self'; font-src 'self' data: https://fonts.gstatic.com; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data: https://cdn.jsdelivr.net https://www.google-analytics.com https://*.cloudfront.net; manifest-src 'self'; media-src 'self'; object-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://*.cloudfront.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.cloudfront.net; worker-src 'self'; upgrade-insecure-requests"
    cross-origin-embedder-policy = "unsafe-none"
    cross-origin-opener-policy = "same-origin"
    cross-origin-resource-policy = "same-origin"
    origin-agent-cluster = "?1"
    referrer-policy = "no-referrer"
    strict-transport-security = "max-age=63072000; includeSubDomains"
    x-content-type-options = "nosniff"
    x-dns-prefetch-control = "off"
    x-download-options = "noopen"
    x-frame-options = "deny"
    x-permitted-cross-domain-policies = "none"
    x-xss-protection = "1; mode=block"

[dev]
  framework = "create-react-app"
  command = "npm run react:start"
  targetPort = 3000
  port = 4000
  envFiles = [".env"]
  autoLaunch = true
  [dev.https]
    certFile = "certs/localhost.crt"
    keyFile = "certs/localhost.key"

[build]
  command = "npm run react:build"
  publish = "build"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true
